insert into offices (id, name, city, state, address, region) values
('office-detroit', 'Detroit HQ', 'Detroit', 'MI', '333 W Fort St, Detroit, MI 48226', 'Midwest'),
('office-troy', 'Troy', 'Troy', 'MI', '5480 Corporate Dr, Troy, MI 48098', 'Midwest'),
('office-chicago', 'Chicago', 'Chicago', 'IL', '150 N Riverside Plaza, Chicago, IL 60606', 'Midwest'),
('office-grand-rapids', 'Grand Rapids', 'Grand Rapids', 'MI', '99 Monroe Ave NW, Grand Rapids, MI 49503', 'Midwest');

insert into users (id, name, email, role, assigned_job_ids, status) values
('user-001', 'T. Smith', 't.smith@doerenmayhew.com', 'Recruiter', ARRAY['job-001','job-002','job-003','job-004','job-005'], 'active'),
('user-002', 'R. Patel', 'r.patel@doerenmayhew.com', 'Hiring Manager', ARRAY['job-001','job-005'], 'active'),
('user-003', 'K. Nguyen', 'k.nguyen@doerenmayhew.com', 'Hiring Manager', ARRAY['job-002'], 'active'),
('user-004', 'J. Brooks', 'j.brooks@doerenmayhew.com', 'Hiring Manager', ARRAY['job-003'], 'active'),
('user-005', 'M. Osei', 'm.osei@doerenmayhew.com', 'Hiring Manager', ARRAY['job-004'], 'active'),
('user-006', 'A. Chen', 'a.chen@doerenmayhew.com', 'Admin', ARRAY[]::text[], 'active'),
('user-007', 'L. Torres', 'l.torres@doerenmayhew.com', 'Admin', ARRAY[]::text[], 'active');

insert into role_workflow_templates (role_key, label, knockout_years, approval_chain, stages) values
('intern', 'Intern', 0, ARRAY['hiring_manager'], '[{"name":"Phone Screen","approver":"Recruiter","slaDays":3},{"name":"Team Interview","approver":"Hiring Manager","slaDays":5},{"name":"Offer","approver":"Hiring Manager","slaDays":3}]'),
('ic', 'Individual Contributor', 1, ARRAY['hiring_manager'], '[{"name":"Phone Screen","approver":"Recruiter","slaDays":3},{"name":"Interview","approver":"Hiring Manager","slaDays":5},{"name":"Offer","approver":"Hiring Manager","slaDays":3}]'),
('manager', 'Manager', 3, ARRAY['hiring_manager','hr_director'], '[{"name":"Phone Screen","approver":"Recruiter","slaDays":3},{"name":"Interview","approver":"Hiring Manager","slaDays":5},{"name":"Panel Interview","approver":"Hiring Manager","slaDays":5},{"name":"Offer","approver":"HR Director","slaDays":3}]'),
('director', 'Director', 8, ARRAY['hiring_manager','hr_director','vp_finance'], '[{"name":"Phone Screen","approver":"Recruiter","slaDays":3},{"name":"Interview","approver":"Hiring Manager","slaDays":5},{"name":"Panel Interview","approver":"Hiring Manager","slaDays":5},{"name":"Executive Interview","approver":"HR Director","slaDays":7},{"name":"Offer","approver":"VP Finance","slaDays":3}]'),
('csuite', 'C-Suite', 12, ARRAY['hiring_manager','hr_director','vp_finance'], '[{"name":"Executive Screen","approver":"HR Director","slaDays":5},{"name":"Board Interview","approver":"VP Finance","slaDays":10},{"name":"Offer","approver":"VP Finance","slaDays":5}]'),
('floor', 'Production Floor', 0, ARRAY['hiring_manager'], '[{"name":"Phone Screen","approver":"Recruiter","slaDays":2},{"name":"In-Person Interview","approver":"Hiring Manager","slaDays":3},{"name":"Offer","approver":"Hiring Manager","slaDays":2}]');

insert into onboarding_packets (state, state_name, documents) values
('MI', 'Michigan', ARRAY['Form I-9 (Employment Eligibility)','Form W-4 (Federal Tax Withholding)','Michigan MI-W4 (State Tax Withholding)','Direct Deposit Authorization','Michigan New Hire Reporting Form','Employee Handbook Acknowledgment']),
('IL', 'Illinois', ARRAY['Form I-9 (Employment Eligibility)','Form W-4 (Federal Tax Withholding)','Illinois IL-W-4 (State Tax Withholding)','Direct Deposit Authorization','Illinois New Hire Reporting Form','Employee Handbook Acknowledgment']);

insert into integrations (id, name, category, description, status, last_sync, new_hire_count, boards, tools) values
('dm-payroll', 'DM Payroll', 'Payroll', 'Auto-syncs new hires straight into payroll the moment an offer is accepted.', 'connected', '2026-07-07 08:14 AM', 12, null, null),
('ms365', 'Microsoft 365 / Outlook', 'Calendar', 'Calendar sync and Teams interview links. Invites are sent from the hiring manager''s own email, not a shared inbox.', 'connected', '2026-07-07 07:02 AM', null, null, null),
('linkedin', 'LinkedIn Recruiter', 'Sourcing', 'One-click candidate import with automatic profile matching against open requisitions.', 'connected', '2026-07-06 04:45 PM', null, null, null),
('job-boards', 'Job Boards', 'Sourcing', 'Posting distribution across external job boards.', 'connected', '2026-07-07 06:00 AM', null, ARRAY['Indeed','ZipRecruiter','Glassdoor'], null),
('background-check', 'Background Check (Sterling)', 'Screening', 'Triggered automatically the moment an offer is accepted.', 'connected', '2026-07-05 11:20 AM', null, null, null),
('drug-screen', 'Drug Screen', 'Screening', 'Ordered alongside the background check on offer acceptance.', 'paused', '2026-06-30 09:15 AM', null, null, null),
('assessments', 'Assessment Tools', 'Assessment', 'Skills, personality, and cognitive assessments, assigned automatically per role template.', 'connected', '2026-07-06 02:30 PM', null, null, ARRAY['Criteria Corp (Skills)','Predictive Index (Personality)','Wonderlic (Cognitive)']),
('dm-payroll-hris', 'DM Payroll HRIS', 'HRIS', 'Benefits eligibility and employee record sync for new hires.', 'not_connected', null, null, null, null);

insert into why_dm_hire_features (icon, title, context, pain, solution, route, action) values
('boards', 'Automated job posting to multiple boards', 'Brandon''s wishlist', 'Recruiters log into LinkedIn, Indeed, Glassdoor, and ZipRecruiter separately for every posting.', 'Select boards once in the requisition. DM Hire distributes to all of them at the same time.', '/jobs', 'Job Requisitions → any open role''s board/link badges'),
('payroll', 'Payroll + onboarding integration', 'Brandon''s wishlist: the whole reason DM Hire exists', 'ClearCompany has no native payroll link, so new hires are manually re-keyed into DM Payroll.', 'Hired candidates auto-sync to DM Payroll the moment they''re marked hired. No re-entry.', '/', 'Dashboard → DM Payroll status card'),
('notifications', 'Automated department notifications', 'Brandon''s wishlist', 'IT, Facilities, and Security find out about a new hire only when someone remembers to email them.', 'A configurable notification matrix decides which department gets notified on which trigger, and what info they receive.', '/settings', 'Settings → Notifications tab'),
('sourceTracking', 'Applicant source tracking', 'Flagged as important to DM specifically', 'Zero visibility into where applicants actually come from; every board looks the same.', 'Every applicant is tagged by source at the moment they apply, rolled up into full conversion and cost reporting.', '/reports', 'Reports → Source ROI table'),
('templates', 'Role-type posting templates', 'Sarah''s wishlist', 'Every requisition, whether intern or C-suite, is built completely from scratch.', 'Six role templates (Intern through C-Suite) pre-fill interview stages, knockout defaults, and the approval chain.', '/jobs', 'Job Requisitions → New Requisition → Role Template'),
('linkedin', 'LinkedIn Recruiter connection', 'Sarah''s wishlist', 'No LinkedIn integration; sourcing and importing candidates is entirely manual.', 'One-click LinkedIn Recruiter import with automatic profile matching to open requisitions.', '/integrations', 'Integrations → LinkedIn Recruiter card'),
('history', 'Prior interaction history indicator', 'Sarah''s wishlist', 'A candidate who applied two years ago for a different role looks brand new to the recruiter today.', 'Prior interactions surface automatically on the pipeline card and candidate profile.', '/pipeline', 'Pipeline → any card with a prior-interaction badge'),
('notes', 'Org-wide shared notes', 'Sarah''s wishlist', 'Notes are siloed to whichever office entered them, so candidates get asked the same questions twice.', 'Every note is visible to every office, with author and location attached.', '/pipeline', 'Any Candidate Profile → Notes tab'),
('esign', 'Electronic offer letters + e-signature', 'Sarah''s wishlist: legal enforceability concern', 'The current "e-signature" is just a timestamped name entry, not a legally binding e-sign.', 'A full e-signature flow with a real audit trail (sent, opened, signed) plus approval routing before it ever reaches the candidate.', '/offers', 'Offers → any offer''s audit trail'),
('sms', 'Candidate text/SMS communication', 'Sarah''s wishlist', 'No native texting; recruiters use personal phones or a separate tool entirely.', 'SMS and email threads live directly on the candidate profile, side by side.', '/pipeline', 'Any Candidate Profile → Comms tab'),
('onboarding', 'State-based onboarding packets', 'Brandon''s wishlist', 'The same onboarding paperwork goes out regardless of which state a new hire works in.', 'Each state has its own configurable document packet, assigned automatically.', '/settings', 'Settings → Onboarding Packets tab'),
('approvals', 'Approval workflows', 'Sarah''s wishlist', 'No configurable approval routing; every requisition and offer moves the same way regardless of level.', 'Role-based approval chains for both requisitions and offers, with status visible at every step.', '/jobs', 'Job Requisitions → any Pending Approval job'),
('duplicates', 'Duplicate candidate detection', 'ClearCompany named as the benchmark: the current DM ATS has nothing', 'Duplicate applicants beyond an exact email match go completely undetected.', 'DM Hire flags likely duplicates before a recruiter wastes time on a repeat application.', '/pipeline?job=job-002', 'Pipeline → job-002 → duplicate-flagged card'),
('navigation', 'Prev/next arrow navigation', 'Quality-of-life ask from recruiters', 'Reviewing a stack of candidates means backing out to the list and reopening each one.', 'Prev/Next arrows step through the exact filtered, sorted list you came from.', '/pipeline', 'Any Candidate Profile → header arrows'),
('aiScore', 'AI qualification scoring', 'Sarah''s wishlist', 'No scoring or qualification signal; recruiters read every resume cold.', 'Every candidate gets an AI match score against the role, broken into five weighted dimensions.', '/pipeline', 'Pipeline → any card''s score badge'),
('offices', 'New office setup + geo-based posting', 'Brandon''s wishlist', 'Adding a new office location isn''t reflected anywhere in how jobs get targeted or posted.', 'Office setup drives geo-based job board targeting automatically.', '/settings', 'Settings → Offices tab'),
('hiringManager', 'Hiring Manager role (screened-only access)', 'Sarah''s wishlist: data governance concern', 'Hiring managers either get full recruiter access or none; there''s no restricted, screened-only view.', 'A dedicated Hiring Manager persona sees only screened candidates on their own jobs, with scorecard submission only and no offer visibility.', '/pipeline', 'Topbar persona switcher → Hiring Manager'),
('outlook', 'Outlook integration', 'Brandon''s wishlist', 'No calendar integration; scheduling is manual back-and-forth email, adding 1-3 days per interview.', 'Interview invites send from the hiring manager''s own Outlook, with Teams links attached automatically.', '/integrations', 'Integrations → Microsoft 365 / Outlook card'),
('scheduler', 'Scheduler tool (Calendly-like)', 'Multiple clients and prospects have asked for this', 'Recruiter emails candidate, candidate replies, recruiter manually builds the invite. Every single time.', 'Candidates self-select from real interviewer availability; the invite goes out automatically.', '/pipeline', 'Any Candidate Profile → Schedule tab'),
('knockout', 'Knockout questions', 'Sarah''s wishlist', 'The current "knockout" is just a waiver acknowledgment, not real disqualifying logic.', 'Per-job knockout rules with a decline note, editable right in the requisition form.', '/jobs', 'New Requisition → Knockout Questions section'),
('scorecards', 'Scorecards', 'Sarah''s wishlist', 'Interview feedback is inconsistent freeform email with no structured comparison across candidates.', 'Every interviewer submits a consistent, dimension-by-dimension scorecard.', '/pipeline', 'Any Candidate Profile → Scorecard tab'),
('portal', 'Mobile-optimized candidate portal', 'Brandon''s wishlist', 'Candidates have no self-service way to apply, check status, or sign an offer from their phone.', 'A dedicated mobile-first candidate portal covers search, apply, status tracking, self-scheduling, and e-sign end to end.', '/portal', 'Candidate Portal (persona switcher → Candidate)'),
('internalJobs', 'Internal job board + internal-only postings', 'Brandon''s wishlist', 'No internal mobility path; current employees find out about openings the same way external applicants do, or not at all.', 'Toggle any requisition Internal Only; employees browse and apply with their existing HRIS record auto-populating the application.', '/internal-jobs', 'Internal Job Board'),
('backgroundCheck', 'Background check + drug screen integrations', 'Brandon''s wishlist', 'Background checks and drug screens are ordered and tracked completely outside the ATS.', 'Both trigger automatically on offer acceptance, with status visible right on the candidate''s Docs tab.', '/integrations', 'Integrations → Background Check / Drug Screen cards'),
('analytics', 'Advanced reporting (TTF, CPH, OAR, IOR)', 'Sarah''s wishlist', 'No analytics layer beyond raw candidate counts; every metric is a manual spreadsheet pull.', 'Time to Fill, Cost per Hire, Offer Acceptance Rate, and Interview-to-Offer Ratio, live from real pipeline data.', '/reports', 'Reports & Analytics'),
('workflows', 'Configurable workflows per role type', 'Sarah''s wishlist', 'Interview stages and approvers are hardcoded; changing them means a vendor support ticket.', 'Every role template''s stages, approvers, and SLAs are editable directly in Settings.', '/settings', 'Settings → Workflows tab'),
('assessments', 'Assessment tool integrations', 'Sarah''s wishlist', 'Skills, personality, and cognitive assessments are ordered and tracked outside the ATS entirely.', 'Criteria Corp, Predictive Index, and Wonderlic all connect directly, assigned automatically per role template.', '/integrations', 'Integrations → Assessment Tools card'),
('jobBoardPerf', 'Job board performance analytics', 'Sarah''s wishlist', 'No visibility into which job board spend is actually converting into hires.', 'One table shows applicants, interviews, hires, conversion rate, and cost by source, with underperformers flagged.', '/reports', 'Reports → Source ROI & Job Board Performance');

insert into analytics (id, data) values ('default', '{
  "timeToFill": {"avg": 18.4, "byDepartment": [{"dept":"Finance","avg":16.2},{"dept":"Client Services","avg":24.5},{"dept":"Human Resources","avg":12.8}], "trend": [{"month":"Jan","value":22},{"month":"Feb","value":20},{"month":"Mar","value":19.5},{"month":"Apr","value":18.1},{"month":"May","value":17.6},{"month":"Jun","value":18.4}]},
  "costPerHire": {"avg": 4210, "bySource": [{"source":"LinkedIn","cost":1200},{"source":"Indeed","cost":800},{"source":"Employee Referral","cost":400},{"source":"Career Site","cost":150},{"source":"ZipRecruiter","cost":650}]},
  "offerAcceptanceRate": {"overall": 0.92, "byRoleType": [{"role":"Manager","rate":0.88},{"role":"IC","rate":0.95},{"role":"Director","rate":0.83}], "trend": [{"month":"Jan","value":0.85},{"month":"Feb","value":0.87},{"month":"Mar","value":0.89},{"month":"Apr","value":0.90},{"month":"May","value":0.91},{"month":"Jun","value":0.92}]},
  "interviewToOfferRatio": {"overall": 4.2, "byDepartment": [{"dept":"Finance","ratio":3.8},{"dept":"Client Services","ratio":5.1},{"dept":"Human Resources","ratio":3.2}]},
  "sourceRoi": [{"source":"LinkedIn","applicants":84,"interviews":22,"hires":9,"conversionRate":0.107,"avgDays":16.2},{"source":"Employee Referral","applicants":31,"interviews":14,"hires":8,"conversionRate":0.258,"avgDays":12.4},{"source":"Career Site","applicants":62,"interviews":11,"hires":4,"conversionRate":0.065,"avgDays":21.1},{"source":"Indeed","applicants":94,"interviews":8,"hires":2,"conversionRate":0.021,"avgDays":24.7},{"source":"ZipRecruiter","applicants":47,"interviews":4,"hires":0,"conversionRate":0,"avgDays":null}]
}'::jsonb);
